---
- name: nginx_start
  docker_container:
    name: nginx
    image: "{{ nginx_image }}"
    state: started
    networks:
      - name: my_network
    ports:
      - "80:80"
    api_version: "1.41"
