---
# tasks file for create_user
- name: Create user
  user:
    name: "{{ username }}"
    state: present
    shell: /bin/bash

- name: Add SSH key to authorized_keys
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', ssh_public_key_path) }}"
    state: present
    exclusive: no 
